project:
  type: website
  output-dir: docs
  
website:
  title: "Ethiopia 2024 Planting Survey"
  navbar:
    left:
      - href: plantng.qmd
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2024, Mohammed"

format:
  html:
    theme:
      - cosmo
      - assets/styles/custom.scss
      - assets/styles/quarto.scss

editor: source

