project:
  type: website
  output-dir: docs
  
website:
  navbar:
    background: primary
    search: true
    left:
      - text: "KPI Data"
        href: plantng.qmd
      - duration.qmd

format:
  html:
    theme:
      - cosmo
      - assets/styles/custom.scss
      - assets/styles/quarto.scss

editor: source

