project:
  type: website
  output-dir: docs
  
website:
  title: "Ethiopia 2024 Planting Survey"
  navbar:
    left:
      - text: "KPI Data"
        href: plantng.qmd
      - text: "Survey Duration"
        href: duration.qmd

format:
  html:
    theme:
      - cosmo
      - assets/styles/custom.scss
      - assets/styles/quarto.scss

editor: source

